version: '3'

services:
  autogen-studio:
    image: autogen-studio-docker:latest
    container_name: autogen-studio-docker
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - autogen-studio-data:/usr/local/lib/python3.11/site-packages/autogenstudio

volumes:
  autogen-studio-data:
    external: true
